# Generated by Django 5.2.8 on 2025-11-25 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_centrocosto_ordencompra_centro_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.producto'),
        ),
    ]
