# Generated by Django 5.2.8 on 2025-11-26 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_detalleorden_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='unidad',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='anticipo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='condiciones_entrega',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='condiciones_pago',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='consecutivo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='criterios_aceptacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='factura_folio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_autorizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='centro_costo',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='compras.centrocosto'),
            preserve_default=False,
        ),
    ]
