# Generated by Django 5.2.8 on 2025-11-27 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_requisicion_detallerequisicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.centrocosto'),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='consecutivo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='fecha_autorizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
