# Generated by Django 5.2.8 on 2025-11-28 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_requisicion_centro_costo_requisicion_consecutivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallerequisicion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.producto'),
        ),
    ]
