# Generated by Django 5.2.8 on 2025-11-28 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_alter_detallerequisicion_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallerequisicion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.producto'),
        ),
    ]
