# Generated by Django 5.2.8 on 2025-11-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_alter_detallerequisicion_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDA', 'Recibida')], default='PENDIENTE', max_length=20),
        ),
    ]
