# Generated by Django 5.2.8 on 2025-12-01 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_ordencompra_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ENTRADA_OC', 'Entrada por Orden de Compra')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('existencia_antes', models.IntegerField()),
                ('existencia_despues', models.IntegerField()),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='compras.producto')),
            ],
        ),
    ]
